### PR TITLE
Task/#220 - Make documentation version button noticeable

### LINKED ISSUE #220: Make documentation version button noticeable
Make version button chooser more noticeable or add another way of choose the version of the documentation.

### PR DESCRIPTION
**Pull request by mike-quiroga**
- Closes #220 - Make documentation version button noticeable

### CODE REVIEW

**Comment by alvaro9210** [comment]
The way of making the button noticeable is a good approach which also works on mobile.
Do you have any specific reason for not including it in the documentation home page?
https://carbonldp.com/documentation/v0.x.x/

**Comment by mike-quiroga** [comment]
@alvaro9210 It uses the same widget but with different styles because of the dark background. I could apply the same approach, what do you think?

**Comment by alvaro9210** [comment]
Yes, please add it to the documentation home page. 
It still looks good with that page design and also makes the version noticeable to users. 👍 
screen shot 2018-02-12 at 2 56 25 pm

**Comment by mike-quiroga** [comment]
@alvaro9210 I applied the blue drop-down on the Documentation page 👍

**Pull request merged**
